scripts: Clean up, add dmenu script

diff --git a/scripts/bri b/scripts/bri
--- a/scripts/bri
+++ b/scripts/bri
@@ -4,6 +4,11 @@
 #
 # Usage: bri, bri [5-100]
 
+command -v xbacklight >/dev/null || {
+    printf 'err: %s\n' "command 'xbacklight' not found."
+    exit 1
+}
+
 if [ -z "$1" ]; then
   xbacklight -get
 elif [ "$1" -gt 100 ]; then
diff --git a/scripts/mon b/scripts/mon
--- a/scripts/mon
+++ b/scripts/mon
@@ -4,6 +4,11 @@
 #
 # Usage: mon, mon [auto]
 
+command -v xrandr >/dev/null || {
+    printf 'err: %s\n' "command 'xrandr' not found."
+    exit 1
+}
+
 [ "$1" = "auto" ] && xrandr --auto
 
 internal_output="$(xrandr | grep "primary" | awk '{print $1}')"
@@ -11,14 +16,14 @@ external_output_1="$(xrandr | grep -w "connected" | awk '{if(NR>1)print $1}' | h
 external_output_2="$(xrandr | grep -w "connected" | awk '{if(NR>2)print $1}')"
 
 if [ -n "$external_output_1" ] && [ -n "$external_output_2" ]; then
-  xrandr \
-    --output "$internal_output" --off \
-    --output "$external_output_1" --auto \
-    --output "$external_output_2" --auto --right-of "$external_output_1"
+    xrandr \
+        --output "$internal_output" --off \
+        --output "$external_output_1" --auto \
+        --output "$external_output_2" --auto --right-of "$external_output_1"
 elif [ -n "$external_output_1" ] && [ -z "$external_output_2" ]; then
-  xrandr \
-    --output "$internal_output" --off \
-    --output "$external_output_1" --auto
+    xrandr \
+        --output "$internal_output" --off \
+        --output "$external_output_1" --auto
 else
   xrandr --auto
 fi
diff --git a/scripts/scl b/scripts/scl
--- a/scripts/scl
+++ b/scripts/scl
@@ -2,6 +2,11 @@
 #
 # Change scaling (resolution) for external monitor(s).
 
+command -v xrandr >/dev/null || {
+    printf 'err: %s\n' "command 'xrandr' not found."
+    exit 1
+}
+
 external_output="$(xrandr | grep -w "connected" | awk '{if(NR>1)print $1}')"
 
 if [[ -z "$external_output" ]]; then
diff --git a/scripts/vol b/scripts/vol
--- a/scripts/vol
+++ b/scripts/vol
@@ -4,6 +4,11 @@
 #
 # Usage: vol, vol [5-100]
 
+command -v pamixer >/dev/null || {
+    printf 'err: %s\n' "command 'pamixer' not found."
+    exit 1
+}
+
 if [ -z "$1" ]; then
   pamixer --get-volume-human
 elif [ "$1" -gt 100 ]; then
