drt: Do it properly

diff --git a/scripts/drt b/scripts/drt
--- a/scripts/drt
+++ b/scripts/drt
@@ -1,40 +1,47 @@
 #!/bin/sh
 
 #
-# drt - dirty directory
+# drt - dirty directory checker
 #
 
 log() {
     printf '%s: %s\n' "$1" "${2##*/}"
 }
 
-for dir in ~/github/bin \
-    ~/projects/bymates \
-    ~/projects/jackieshop \
-    ~/packages/st \
-    ~/packages/sowm \
-    ~/dotfiles \
-    ~/.vim/plugged/cs.vim \
-    ~/.vim/plugged/sl.vim \
-    ~/github/cpr \
-    ~/github/todo \
-    ~/github/typography \
-    ~/github/onemoresalary \
-    ~/github/fehawen-files \
-    ~/github/lipp \
-    ~/github/rpg; do
-    (
-        [ -d $dir ] || {
-            log "nodir" "$dir"
-        }
+main() {
+    [ -z "$DRT_PATH" ] && {
+        printf '%s\n' "DRT_PATH is not set."
+        exit
+    }
 
-        cd $dir 2> /dev/null || exit
+    set -f
 
-        command git rev-parse --is-inside-work-tree 1> /dev/null 2> /dev/null || {
-            log "nogit" "$dir"
-            exit
-        }
+    IFS=':'
 
-        [ -z "$(git status --short 2> /dev/null)" ] || log "dirty" "$dir"
-    )
-done
+    # shellcheck disable=2086
+    set -- $DRT_PATH
+
+    for dir in "$@"; do
+        (
+            [ -d "$dir" ] || {
+                log "Not a directory" "$dir"
+            }
+
+            cd "$dir" 2> /dev/null || {
+                log "Failed to change directory to" "$dir"
+                exit
+            }
+
+            command git rev-parse --is-inside-work-tree 1> /dev/null 2> /dev/null || {
+                log "Not a git directory" "$dir"
+                exit
+            }
+
+            [ -z "$(git status --short 2> /dev/null)" ] || log "dirty" "$dir"
+        )
+    done
+
+    set +f
+}
+
+main
